devgateway/amp

amp/WEB-INF/src/org/digijava/kernel/ampapi/endpoints/activity/FieldIdValue.java
amp/WEB-INF/src/org/digijava/kernel/ampapi/endpoints/activity/InterchangeEndpoints.java
amp/WEB-INF/src/org/digijava/kernel/ampapi/endpoints/activity/LocationExtraInfo.java
amp/WEB-INF/src/org/digijava/kernel/ampapi/endpoints/activity/ParentExtraInfo.java
amp/WEB-INF/src/org/digijava/kernel/ampapi/endpoints/activity/PossibleValue.java
amp/WEB-INF/src/org/digijava/kernel/ampapi/endpoints/activity/PossibleValuesDAO.java
amp/WEB-INF/src/org/digijava/kernel/ampapi/endpoints/activity/PossibleValuesEnumerator.java
amp/WEB-INF/src/org/digijava/kernel/ampapi/endpoints/activity/ProgramExtraInfo.java
amp/WEB-INF/src/org/digijava/kernel/ampapi/endpoints/activity/SectorExtraInfo.java

AMP-28308: Create endpoint for displaying values for requested fields

---

amp/WEB-INF/src/org/dgfoundation/amp/currencyconvertor/AmpCurrencyConvertor.java
amp/WEB-INF/src/org/digijava/kernel/ampapi/endpoints/activity/ActivityEPConstants.java
amp/WEB-INF/src/org/digijava/kernel/ampapi/endpoints/activity/InterchangeEndpoints.java
amp/WEB-INF/src/org/digijava/kernel/ampapi/endpoints/activity/preview/AmountSerializer.java
amp/WEB-INF/src/org/digijava/kernel/ampapi/endpoints/activity/preview/PreviewActivityFunding.java
amp/WEB-INF/src/org/digijava/kernel/ampapi/endpoints/activity/preview/PreviewActivityService.java
amp/WEB-INF/src/org/digijava/kernel/ampapi/endpoints/activity/preview/PreviewFunding.java
amp/WEB-INF/src/org/digijava/kernel/ampapi/endpoints/activity/preview/PreviewFundingDetail.java
amp/WEB-INF/src/org/digijava/kernel/ampapi/endpoints/activity/preview/PreviewFundingInformation.java
amp/WEB-INF/src/org/digijava/kernel/ampapi/endpoints/activity/preview/PreviewFundingTotal.java
amp/WEB-INF/src/org/digijava/kernel/ampapi/endpoints/activity/preview/PreviewFundingTransaction.java
amp/WEB-INF/src/org/digijava/module/aim/dbentity/AmpFunding.java
amp/WEB-INF/src/org/digijava/module/aim/dbentity/AmpFundingDetail.java
amp/WEB-INF/src/org/digijava/module/aim/dbentity/AmpFundingMTEFProjection.java
amp/WEB-INF/src/org/digijava/module/common/util/DateTimeUtil.java

AMP-28314: Create endpoint for fetching funding information for activity

---

amp/TEMPLATE/ampTemplate/node_modules/amp-filter/src/collections/all-filters-collection.js
amp/TEMPLATE/ampTemplate/node_modules/amp-filter/src/models/generic-filter-model.js
amp/TEMPLATE/ampTemplate/node_modules/amp-filter/src/models/years-filter-model.js
amp/TEMPLATE/ampTemplate/node_modules/amp-filter/src/tree/tree-node-view.js
amp/TEMPLATE/ampTemplate/node_modules/amp-filter/src/utils/constants.js
amp/TEMPLATE/ampTemplate/node_modules/amp-filter/src/views/base-filter-view.js
amp/TEMPLATE/ampTemplate/node_modules/amp-filter/src/views/filters-view.js
amp/TEMPLATE/ampTemplate/node_modules/amp-filter/src/views/years-filter-view.js
amp/TEMPLATE/ampTemplate/node_modules/amp-filter/src/views/years-only-filter-view.js

AMP-27454 FE - Update the fields definitions for list filters

AMP-27454 FE - Update the fields definitions for list filters

---

amp/WEB-INF/src/org/digijava/module/aim/action/CompareActivityVersions.java
amp/WEB-INF/src/org/digijava/module/aim/util/ActivityVersionUtil.java

Revert "Task/ampet-141/compare-to-previous-final-m"

---

amp/TEMPLATE/ampTemplate/gisModule/dev/app/js/amp/data/collections/structures-collection.js
amp/TEMPLATE/ampTemplate/gisModule/dev/app/js/amp/map/views/structures-view.js

AMP-28751 Fix project site issue that occurs when some activities do not
have planned disbursements or planned commitments

AMP-28751 Fix project site issue

---

amp/WEB-INF/src/org/digijava/kernel/ampapi/endpoints/gis/GisEndPoints.java
amp/WEB-INF/src/org/digijava/kernel/ampapi/endpoints/gis/services/LocationService.java

AMP-28751 error while selecting planned measure in settings- apply changes for AMP-28301on version 3.2.3

AMP-28751 Error while selecting planned measure in settings

---

amp/TEMPLATE/ampTemplate/gisModule/dev/app/js/amp/data/collections/structures-collection.js
amp/TEMPLATE/ampTemplate/gisModule/dev/app/js/amp/map/views/structures-view.js

Revert "AMP-28751 Fix project site issue"

---

amp/TEMPLATE/ampTemplate/gisModule/dev/app/js/amp/data/collections/structures-collection.js
amp/TEMPLATE/ampTemplate/gisModule/dev/app/js/amp/map/views/structures-view.js

AMP-28751 Fix project site issue that occurs when some activities do not
have planned disbursements or planned commitments

AMP-28751 Fix project site issue 3.2.3

---

amp/TEMPLATE/reamp/modules/admin/performance-alert-manager/components/PerformanceRuleForm.jsx
amp/TEMPLATE/reamp/modules/admin/performance-alert-manager/components/PerformanceRuleRow.jsx

AMP-28713 Update performance rule module FE after EP changes

AMP-28713 Update performance rule module FE after EP changes

---

amp/TEMPLATE/ampTemplate/gisModule/dev/app/js/amp/map/legend/legend-item-indicator-join.js
amp/TEMPLATE/ampTemplate/gisModule/dev/app/js/amp/map/views/indicator-layers-view.js
amp/TEMPLATE/ampTemplate/node_modules/gis-layers-manager/src/templates/wizard-template.html
amp/TEMPLATE/ampTemplate/node_modules/gis-layers-manager/src/views/admin-view.js
amp/TEMPLATE/ampTemplate/node_modules/gis-layers-manager/src/views/share-workspace-view.js
amp/TEMPLATE/ampTemplate/node_modules/gis-layers-manager/src/views/wizard-view.js

AMP-28617 Update Indicator Layer Manager and GIS in order to fetch data correctly from indicator endpoints

AMP-28617 Update Indicator Layer Manager and GIS after BE refactoring

---

amp/WEB-INF/src/org/digijava/kernel/ampapi/endpoints/common/EndpointUtils.java
amp/WEB-INF/src/org/digijava/kernel/ampapi/endpoints/common/NiFiltersEndpoint.java

Fix visibility for approval status filter.

AMP-28757: Configure grouping for financing instrument filter. 

---

amp/TEMPLATE/ampTemplate/node_modules/amp-filter/src/collections/all-filters-collection.js
amp/TEMPLATE/ampTemplate/node_modules/amp-filter/src/utils/constants.js

AMP-28705 Issue - Donor list behavior inconsistent with development list

AMP-28705 Issue - Donor list behavior inconsistent with development list

---

amp/TEMPLATE/ampTemplate/gisModule/dev/app/js/amp/data/models/indicator-join-model.js

AMP-28747 Update how GIS FE fetches statistical layers data - use
separate EP for gap analysis

AMP-28747 Update how GIS FE fetches statistical layers data

---

amp/WEB-INF/src/org/digijava/module/aim/action/CompareActivityVersions.java
amp/repository/aim/view/auditLoggerManager.jsp
amp/repository/aim/view/viewActivityDifferences.jsp

This new branch contains changes needed to add a new button on audit logger to compare an activity with its previous version.

AMPET-108: Modify audit logger add button

---

amp/TEMPLATE/ampTemplate/node_modules/amp-filter/src/less/amp-filters.less
amp/TEMPLATE/ampTemplate/node_modules/amp-filter/src/less/datepicker.less
amp/TEMPLATE/ampTemplate/node_modules/amp-filter/src/lib/initial-translation-request.json
amp/TEMPLATE/ampTemplate/node_modules/amp-filter/src/templates/years-template.html
amp/TEMPLATE/ampTemplate/node_modules/amp-filter/src/views/years-filter-view.js

AMP-24341 Filters: Improve datepickers

AMP-24341 Filters: Improve datepickers

---

amp/WEB-INF/src/org/digijava/module/aim/action/CompareActivityVersions.java
amp/repository/aim/view/auditLoggerManager.jsp
amp/repository/aim/view/viewActivityDifferences.jsp

Restoring https://github.com/devgateway/amp/pull/2758

Task/ampet 108/modify audit logger add button

---

amp/TEMPLATE/ampTemplate/node_modules/amp-filter/src/less/amp-filters.less
amp/TEMPLATE/ampTemplate/node_modules/amp-filter/src/views/years-filter-view.js

AMP-28869 Datepicker UI improvements

AMP-28869 Datepicker UI improvements

---

amp/TEMPLATE/ampTemplate/node_modules/amp-filter/src/collections/all-filters-collection.js
amp/TEMPLATE/ampTemplate/node_modules/amp-filter/src/templates/subfilter-title-template.html
amp/TEMPLATE/ampTemplate/node_modules/amp-filter/src/views/filters-view.js
amp/TEMPLATE/ampTemplate/node_modules/amp-filter/src/views/top-level-filter-view.js

AMP-28860 Filter agencies alphabetic order on left tabs of filters

AMP-28860 Filter agencies alphabetic order on left tabs of filters

---

amp/WEB-INF/src/org/digijava/kernel/ampapi/endpoints/config/utils/ConfigHelper.java
amp/WEB-INF/src/org/digijava/module/aim/services/auditcleaner/AuditCleanerJob.java
amp/repository/aim/view/viewGlobalSettings.jsp
amp/xmlpatches/2.z13.05/AMPET-148-audit-logger-cleaner.xml
amp/xmlpatches/general/views/v_g_settings_audit_logger_cleanup.xml

Change the way possible values are configured on this particular global settings..

AMPET-148: Add possible values for automatic audit logs cleanup

---

amp/TEMPLATE/ampTemplate/node_modules/amp-filter/src/collections/all-filters-collection.js

AMP-28866 FIlter by ALL Organizations does not keep some of the items in
the tree

AMP-28866 FIlter by ALL orgs does not keep some of the items in the tree

---

amp/TEMPLATE/ampTemplate/node_modules/amp-filter/src/templates/generic-filter-template.html
amp/TEMPLATE/ampTemplate/node_modules/amp-filter/src/views/generic-filter-view.js

AMP-28888 Issue - remove select all/deselect all from filters

AMP-28888 Issue - remove select all/deselect all from filters

---

amp/TEMPLATE/ampTemplate/node_modules/amp-filter/src/views/years-only-filter-view.js

AMP-27131 Computed year applied filter not shown in Filter left panel

AMP-27131 Computed year applied filter not shown in Filter left panel

---

amp/TEMPLATE/ampTemplate/node_modules/amp-filter/src/collections/all-filters-collection.js

AMP-28861 Orgs are not alphabetically sorted in Filter right part

AMP-28861 Orgs are not alphabetically sorted in Filter right part

---

amp/WEB-INF/src/org/digijava/kernel/ampapi/endpoints/filters/ComputedYearFilterListManager.java

AMP-27555 Settings of year range for computed year filter

AMP-27555 Settings of year range for computed year filter

---

amp/TEMPLATE/ampTemplate/node_modules/amp-filter/src/views/years-filter-view.js
amp/repository/aim/view/ar/reportsScripts.jsp
amp/repository/aim/view/query/queryEngine.jsp

AMP-28925 datepicker error after reset

AMP-28925 datepicker error after reset

---

amp/repository/aim/view/pledgeform/pledgeIdentification.jsp
amp/repository/bootstrap/amp-bootstrap.css

AMP-28893 Add vertical scrolling in pledge organization group dropdown

AMP-28893 Add vertical scrolling in pledge organization group dropdown

---

amp/TEMPLATE/ampTemplate/dashboard/dev/app/js/app/views/chart-aid-predictability.js

AMP-28236 Aid predictability chart issue

AMP-28236 Aid predictability chart issue

---

amp/WEB-INF/src/org/digijava/module/aim/action/CompareActivityVersions.java
amp/WEB-INF/src/org/digijava/module/aim/form/CompareActivityVersionsForm.java
amp/WEB-INF/src/org/digijava/module/aim/util/ActivityVersionUtil.java
amp/WEB-INF/src/org/digijava/module/aim/util/AuditLoggerUtil.java
amp/repository/aim/view/auditLoggerManager.jsp
amp/repository/aim/view/viewActivityDifferences.jsp
amp/repository/aim/view/viewGroupedOutput.jsp

Add the functionality to export a full list of activities, compared to its previous versions.

AMPET-109: Show changes from all activities in audit logger

---

amp/WEB-INF/src/org/dgfoundation/amp/reports/saiku/export/ExportFilterUtils.java

AMP-28910 Issue - report exports don't have info about undefined filters

AMP-28910 Issue - report exports don't have info about undefined filters

---

amp/WEB-INF/src/org/digijava/module/aim/action/ReportsFilterPicker.java

AMP-29014 clear undefined options collection before adding new items

AMP-29014 clear undefined options collection before adding new items

---

amp/TEMPLATE/ampTemplate/css_2/amp.css
amp/TEMPLATE/ampTemplate/node_modules/amp-filter/src/less/amp-filters.less
amp/TEMPLATE/ampTemplate/node_modules/amp-filter/src/templates/filters-content-template.html
amp/repository/aim/view/scripts/reportWizard/filterWidgetLoader.js

AMP-28923 show Loading status when loading results of the filter

AMP-28923 show Loading status when loading results of the filter

---

amp/TEMPLATE/reamp/modules/activity-preview/dev.html
amp/TEMPLATE/reamp/modules/activity-preview/index.html
amp/TEMPLATE/reamp/modules/admin/currency/deflator/index.html
amp/TEMPLATE/reamp/modules/admin/dashboard/index.html
amp/TEMPLATE/reamp/modules/admin/data-freeze-manager/index.html
amp/TEMPLATE/reamp/modules/admin/performance-alert-manager/index.html
amp/TEMPLATE/reamp/modules/admin/resource-manager-admin/index.html
amp/TEMPLATE/reamp/modules/ampoffline/download/index.html
amp/TEMPLATE/reamp/modules/gpi-data/index.html
amp/TEMPLATE/reamp/modules/gpi-reports/common/Utils.jsx
amp/TEMPLATE/reamp/modules/gpi-reports/index.html
amp/TEMPLATE/reamp/webpack.config.js

AMP-28006 modify reamp build to create separate bundle for dependencies

AMP-28006 modify reamp build to create separate bundle for dependencies

---

amp/TEMPLATE/ampTemplate/node_modules/amp-filter/src/collections/all-filters-collection.js
amp/TEMPLATE/ampTemplate/node_modules/amp-filter/src/templates/years-only-template.html

AMP-29024 Existing translation strings not used

AMP-29024 Existing translation strings not used

---

amp/WEB-INF/src/org/dgfoundation/amp/ar/AmpARFilter.java
amp/WEB-INF/src/org/dgfoundation/amp/reports/converters/AmpARFilterConverter.java
amp/WEB-INF/src/org/digijava/module/aim/action/ReportsFilterPicker.java
amp/WEB-INF/src/org/digijava/module/aim/ar/util/FilterUtil.java
amp/WEB-INF/src/org/digijava/module/aim/form/ReportsFilterPickerForm.java

AMP-29326: Add 'Actual Approval Date' filter to the old filter widget (2.13.3.2)

---

amp/TEMPLATE/ampTemplate/saikuui_reports/js/saiku/plugins/AMPFilters/plugin.js
amp/TEMPLATE/ampTemplate/saikuui_reports/mockData/plugins.json

AMP-29427 filters not translatable

---

amp/TEMPLATE/ampTemplate/site-config.xml
amp/TEMPLATE/reamp/package.json
amp/pom.xml

AMP-29773 adjut version release

---

amp/WEB-INF/src/org/digijava/kernel/ampapi/endpoints/activity/PossibleValuesEnumerator.java

AMP-30347: Better errors when retrieving possible values fails

AMP-30347-errors-in-pv

---

amp/WEB-INF/src/org/digijava/module/aim/util/LocationSkeleton.java
amp/xmlpatches/3.5.05.1/AMP-30423-update-empty-gs-lat-and-long-to-null.xml

AMP-30423 update empty lat & long

---

amp/TEMPLATE/reamp/package-lock.json
amp/TEMPLATE/reamp/package.json

This pr gonna point to https://github.com/devgateway/amp-ui/pull/188/commits (amp-ui) until we are sure the fix is fine.. then we need to point to amp-ui develop branch

AMP-30469 issue- AP -error in console

---

amp/TEMPLATE/reamp/modules/activity/preview/actions/ActivityActions.jsx
amp/TEMPLATE/reamp/package-lock.json

AMP-30698 - Issue on some activities preview from Uganda

---

amp/TEMPLATE/reamp/package-lock.json
amp/TEMPLATE/reamp/package.json

Change amp-ui linked on package.json

AMP-30691 - DRC - Activity Preview Export to word not works

---

amp/WEB-INF/src/org/digijava/kernel/ampapi/endpoints/activity/ActivityInterchangeUtils.java
amp/xmlpatches/3.5.05.1/AMP-30372-add-hide-document-setting.xml
amp/xmlpatches/3.5.05.1/AMP-30515-Add-hide-empty-total-settings.xml

The problem was with inserts into amp_modules_visibility

AMP-30682 - problem to deploy on Chad

---

amp/WEB-INF/src/org/digijava/kernel/ampapi/endpoints/common/EPConstants.java

Fix preview report adding "R" value to REPORT_TYPE_ID_MAP property

AMP-30707 - ISSUE - Ethiopia - Regional Reports
